### ISSUE TITLE
[LayoutConstraints] Unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by susuyan** [Kofktu/KUITagLabel#3]
<img width="856" alt="2018-11-01 15 51 45" src="https://user-images.githubusercontent.com/7692197/47839638-63231a80-ddee-11e8-9d42-cc1eb2e2b16d.png">

**Comment by Kofktu** [comment]
I'll check and fix it.

**Comment by susuyan** [comment]
thanks
